name: hola-mundo

on: 
  workflow_dispatch: 
  #schedule:
  #  - cron: "*/5 * * * *" # Se ejecuta cada 5 minutos. 
  #push:
  #  branches: 
  #  - main

jobs:
  saludar:
    runs-on: windows-latest
    steps:
      - name: Muestra mensje hola mundo
        run: echo "Hola mundo!! Israel"

      - name: Checkout
        uses: actions/checkout@v7.0.1
        
      - name: Listar archivos del respositorio
        run: | 
          echo "El repositorio $({ gihub.repository }) contiene los siguientes archivos:"
          tree
